
// ==========================================
// Risk Evaluations Tab Logic
// ==========================================

// Tool Descriptions Data (Subset for UI representation)
const toolDescriptionsMap = {
  // Cybersecurity Tools
  'prompt-injection-detector': { name: 'Prompt Injection Detection Assessment', category: 'Cybersecurity', description: 'Detects and prevents prompt injection attacks in AI systems.' },
  'security-frameworks': { name: 'Security Frameworks', category: 'Cybersecurity', description: 'Implements comprehensive security frameworks and best practices.' },
  'grype-vulnerability': { name: 'Grype Vulnerability Scanner', category: 'Cybersecurity', description: 'Scans container images and filesystems for known vulnerabilities.' },
  'safety-pyup': { name: 'Safety (PyUp)', category: 'Cybersecurity', description: 'Checks Python dependencies for known security vulnerabilities.' },
  'snyk-io': { name: 'Snyk', category: 'Cybersecurity', description: 'Finds and fixes vulnerabilities in code, dependencies, and containers.' },
  'oss-scorecard': { name: 'OSS Scorecard', category: 'Cybersecurity', description: 'Assesses security posture of open-source projects.' },
  
  // Privacy
  'data-classification': { name: 'Data Classification', category: 'Privacy', description: 'Automatically classifies and labels sensitive data.' },
  'gdpr-compliance': { name: 'GDPR Compliance', category: 'Privacy', description: 'Toolkit for ensuring GDPR compliance in AI systems.' },
  'hipaa-compliance': { name: 'HIPAA Compliance', category: 'Privacy', description: 'Ensures compliance with HIPAA regulations for healthcare data.' },
  'pci-dss-compliance': { name: 'PCI DSS Compliance', category: 'Privacy', description: 'Validates compliance with PCI DSS for payment card data.' },
  
  // Fundamental Rights (FRIA)
  'fria-assessment': { name: 'FRIA Assessment', category: 'Fundamental Rights', description: 'Comprehensive assessment of AI system impact on fundamental rights.' },
  'bias-assessment': { name: 'Bias Assessment', category: 'Fundamental Rights', description: 'Evaluates AI models for potential biases and discriminatory outcomes.' },
  'ai-fairness-360': { name: 'AI Fairness 360', category: 'Fundamental Rights', description: 'IBM toolkit to examine, report, and mitigate discrimination and bias.' },
  'hitl-design': { name: 'HITL Design', category: 'Fundamental Rights', description: 'Human-in-the-Loop design ensuring human oversight in AI decision making.' },

  // Societal
  'detoxify': { name: 'Detoxify', category: 'Societal', description: 'Detects toxic comments and harmful content.' },
  'hate-speech-detector': { name: 'Hate Speech Detector', category: 'Societal', description: 'Identifies hate speech and discriminatory language.' },
  'claimbuster-api': { name: 'ClaimBuster API', category: 'Societal', description: 'Automated fact-checking and claim spotting.' },
  'fact-checker': { name: 'Fact Checker', category: 'Societal', description: 'Verifies the factual accuracy of AI generated content.' },
  'ai-content-detector': { name: 'AI Content Detector', category: 'Societal', description: 'Identifies content generated by AI systems.' },
  'perspective-api-societal': { name: 'Perspective API (Societal)', category: 'Societal', description: 'Analyzes text for potential impact on conversation quality.' },
  'textblob-sentiment': { name: 'TextBlob Sentiment', category: 'Societal', description: 'Simple sentiment analysis for text processing.' },
  'vader-sentiment': { name: 'VADER Sentiment', category: 'Societal', description: 'Sentiment analysis tuned for social media text.' },

  // Fairness & Bias Detection
  // 'ai-fairness-360' (Reused)
  'fairlearn': { name: 'Fairlearn', category: 'Fairness', description: 'Assesses and improves fairness of machine learning models.' },
  'aequitas': { name: 'Aequitas', category: 'Fairness', description: 'Bias and fairness audit toolkit.' },
  // 'bias-assessment' (Reused)
  'disaggregated-evaluation': { name: 'Disaggregated Evaluation', category: 'Fairness', description: 'Evaluates model performance across different subgroups.' },
  'perspective-api': { name: 'Perspective API', category: 'Fairness', description: 'Identifies toxicity and bias in text.' },
  'moderate-content-api': { name: 'Moderate Content API', category: 'Fairness', description: 'Content moderation and safety filtering tools.' },

  // Trust & Explainability
  'explainability-planning': { name: 'Explainability Planning', category: 'Trust', description: 'Strategic framework for designing explainable AI systems.' },
  'shap-explainer': { name: 'SHAP', category: 'Trust', description: 'Explains machine learning model predictions.' },
  'lime': { name: 'LIME', category: 'Trust', description: 'Local Interpretable Model-agnostic Explanations.' },
  'captum': { name: 'Captum', category: 'Trust', description: 'Model interpretability and understanding for PyTorch.' },
  'interpretml': { name: 'InterpretML', category: 'Trust', description: 'Unified framework for machine learning interpretability.' },
  'what-if-tool': { name: 'What-If Tool', category: 'Trust', description: 'Interactive visual interface for model understanding.' },
  'ai-transparency-labels': { name: 'AI Transparency Labels', category: 'Trust', description: 'Standardized labels for AI system transparency.' },
  'model-card-generation': { name: 'Model Card Generation', category: 'Trust', description: 'Automates creation of model cards for documentation.' },
  // 'hitl-design' (Reused)

  // Health and Safety
  'ai-safety': { name: 'AI Safety', category: 'Health & Safety', description: 'General safety protocols for AI systems.' },
  'ai-safety-planning': { name: 'AI Safety Planning', category: 'Health & Safety', description: 'Framework for planning safe AI deployment.' },
  'red-team-testing': { name: 'Red Team Testing', category: 'Health & Safety', description: 'Adversarial testing to identify safety failures.' },
  'guardrails-implementation': { name: 'Guardrails Implementation', category: 'Health & Safety', description: 'Implements operational boundaries for AI behavior.' },
  'risk-assessment': { name: 'Risk Assessment', category: 'Health & Safety', description: 'General risk evaluation methodologies.' },
  'incident-responder': { name: 'Incident Responder', category: 'Health & Safety', description: 'Tools for managing and responding to AI incidents.' },

  // Performance Testing & Monitoring
  'evidently-ai': { name: 'Evidently AI', category: 'Performance', description: 'Monitors ML models in production.' },
  'alibi-detect': { name: 'Alibi Detect', category: 'Performance', description: 'Outlier, adversarial and drift detection.' },
  'ragas': { name: 'Ragas', category: 'Performance', description: 'Evaluation framework for RAG pipelines.' },
  'deepeval': { name: 'DeepEval', category: 'Performance', description: 'Evaluation framework for LLMs.' },
  'huggingface-evaluate': { name: 'Hugging Face Evaluate', category: 'Performance', description: 'Library for evaluating ML models and datasets.' },
  'langsmith': { name: 'LangSmith', category: 'Performance', description: 'DevOps platform for LLM applications.' },
  'weights-and-biases': { name: 'Weights & Biases', category: 'Performance', description: 'Machine learning experiment tracking.' },
  'promptfoo': { name: 'Promptfoo', category: 'Performance', description: 'Tool for testing and evaluating LLM prompts.' },

  // Governance & Documentation
  'ai-ethics': { name: 'AI Ethics', category: 'Governance', description: 'Frameworks for ethical AI development.' },
  'ai-ethics-advisor': { name: 'AI Ethics Advisor', category: 'Governance', description: 'Advisory tools for ethical decision making.' },
  'ai-governance': { name: 'AI Governance', category: 'Governance', description: 'End-to-end AI governance management.' },
  'ethics-review': { name: 'Ethics Review', category: 'Governance', description: 'Structured review process for AI ethics.' },
  'validating-ai-ethics-and-fairness': { name: 'Validating Ethics', category: 'Governance', description: 'Validation tools for ethics and fairness claims.' },
  'ai-logging-system': { name: 'AI Logging System', category: 'Governance', description: 'Comprehensive logging for AI system activities.' },
  'ai-system-registry': { name: 'AI System Registry', category: 'Governance', description: 'Centralized registry for AI system tracking.' },
  'qms-tracker': { name: 'QMS Tracker', category: 'Governance', description: 'Quality Management System tracking for AI.' },
  'ce-marking-generator': { name: 'CE Marking Generator', category: 'Governance', description: 'Assists with CE marking documentation.' },

  // Environmental
  'codecarbon': { name: 'CodeCarbon', category: 'Environmental', description: 'Tracks CO2 emissions from computing.' },
  'cloud-carbon-footprint': { name: 'Cloud Carbon Footprint', category: 'Environmental', description: 'Measures carbon usage of cloud usage.' },
  'ml-co2-impact': { name: 'ML CO2 Impact', category: 'Environmental', description: 'Calculates carbon impact of machine learning.' },
  'watttime-carbon': { name: 'WattTime Carbon', category: 'Environmental', description: 'Real-time grid emission data integrator.' }
};

// Skill Assessments Data (Structured Questions)
const skillAssessments = {
    'fria-assessment': {
        skillId: 'fria-assessment',
        name: 'Fundamental Rights Impact Assessment (FRIA)',
        category: 'Fundamental Rights',
        description: 'Conducts comprehensive assessment of AI system impact on fundamental rights including privacy, non-discrimination, and human dignity per Article 27.',
        article: 'Article 27',
        sections: [
          {
            id: 'rights-identification',
            title: 'Fundamental Rights Identification',
            description: 'Identify which fundamental rights may be impacted by your AI system',
            questions: [
              {
                id: 'affected-rights',
                question: 'Which fundamental rights may be affected by your AI system?',
                type: 'checkbox',
                options: [
                  'Right to privacy and data protection (Article 8 CFR)',
                  'Right to non-discrimination (Article 21 CFR)',
                  'Right to human dignity (Article 1 CFR)',
                  'Freedom of expression and information (Article 11 CFR)',
                  'Right to fair trial and defense (Article 47-48 CFR)',
                  'Rights of the child (Article 24 CFR)',
                  'Consumer protection',
                  'Workers\' rights',
                  'Right to an effective remedy (Article 47 CFR)'
                ],
                required: true
              },
              {
                id: 'vulnerable-groups',
                question: 'Does the system affect vulnerable groups?',
                type: 'checkbox',
                options: ['Children', 'Elderly', 'Persons with disabilities', 'Minorities', 'Refugees', 'None identified'],
                required: true
              },
              {
                id: 'rights-severity',
                question: 'What is the potential severity of impact on fundamental rights?',
                type: 'radio',
                options: [
                  'Critical - Severe and irreversible harm',
                  'High - Significant harm with lasting effects',
                  'Medium - Moderate impact with mitigation possible',
                  'Low - Minimal or negligible impact',
                  'Not yet assessed'
                ],
                required: true
              }
            ]
          },
          {
             id: 'privacy-impact',
             title: 'Privacy and Data Protection Impact',
             description: 'Assess impact on privacy and data protection rights',
             questions: [
                 {
                     id: 'personal-data-processing',
                     question: 'What types of personal data does the system process?',
                     type: 'checkbox',
                     options: [
                         'Basic personal data (name, address, etc.)',
                         'Special categories (race, health, biometric, etc.)',
                         'Behavioural data',
                         'Location data',
                         'Financial data',
                         'Children\'s data',
                         'None'
                     ],
                     required: true
                 },
                 { id: 'data-subject-consent', question: 'Have data subjects provided informed consent or is there another lawful basis?', type: 'yes-no', required: true, helpText: 'GDPR requires a lawful basis for processing personal data' },
                 { id: 'privacy-by-design', question: 'Are privacy-by-design principles implemented?', type: 'yes-no', required: true },
                 { id: 'dpia-conducted', question: 'Has a Data Protection Impact Assessment (DPIA) been conducted?', type: 'yes-no', required: true, helpText: 'GDPR Article 35 requires DPIA for high-risk processing' }
             ]
          },
          {
             id: 'discrimination-impact',
             title: 'Non-Discrimination and Fairness Impact',
             description: 'Assess risks of discrimination and unfair treatment',
             questions: [
                 { id: 'protected-characteristics', question: 'Does the system make decisions based on or affecting protected characteristics?', type: 'yes-no', required: true },
                 {
                     id: 'discrimination-risk',
                     question: 'What is the risk of discriminatory outcomes?',
                     type: 'radio',
                     options: [
                         'High - System directly uses protected attributes',
                         'Medium - Proxy variables may lead to discrimination',
                         'Low - Measures in place to prevent discrimination',
                         'Negligible - No discrimination risk identified',
                         'Not yet assessed'
                     ],
                     required: true
                 },
                 { id: 'bias-testing', question: 'Has the system been tested for bias across different demographic groups?', type: 'yes-no', required: true },
                 { id: 'fairness-metrics', question: 'Are fairness metrics monitored during operation?', type: 'yes-no', required: true, helpText: 'Article 10 requires monitoring for bias' }
             ]
          },
          {
             id: 'transparency-impact',
             title: 'Transparency and Explainability',
             description: 'Assess transparency and users\' understanding of the system',
             questions: [
                 { id: 'user-awareness', question: 'Are users aware they are interacting with an AI system?', type: 'yes-no', required: true, helpText: 'Article 52 requires disclosure of AI use' },
                 { id: 'decision-explanation', question: 'Can the system provide explanations for its decisions?', type: 'yes-no', required: true },
                 {
                     id: 'information-provided',
                     question: 'What information is provided to affected individuals?',
                     type: 'checkbox',
                     options: [
                         'Purpose of the AI system',
                         'Type of decisions made',
                         'Logic involved',
                         'Significance and consequences',
                         'How to contest decisions',
                         'Contact information for queries',
                         'Limited or no information provided'
                     ],
                     required: true
                 }
             ]
          },
          {
             id: 'human-oversight',
             title: 'Human Agency and Oversight',
             description: 'Assess human control and intervention capabilities',
             questions: [
                 {
                     id: 'human-oversight-level',
                     question: 'What level of human oversight is implemented?',
                     type: 'radio',
                     options: [
                         'Human-in-the-loop (decision requires human approval)',
                         'Human-on-the-loop (human can intervene)',
                         'Human-in-command (human can override)',
                         'Fully automated with no human oversight',
                         'Not yet determined'
                     ],
                     required: true
                 },
                 { id: 'override-mechanism', question: 'Can humans override or reverse AI decisions?', type: 'yes-no', required: true, helpText: 'Article 14 requires human oversight measures' },
                 { id: 'contestability', question: 'Is there a mechanism for individuals to contest decisions?', type: 'yes-no', required: true }
             ]
          }
        ]
    },
    // Default assessment with 5 sections for all other tools
    'default': {
        skillId: 'default',
        name: 'Compliance Assessment',
        category: 'General',
        description: 'Comprehensive compliance assessment for AI systems.',
        sections: [
            {
                id: 'system-overview',
                title: 'System Overview',
                description: 'Basic information about your AI system and its deployment',
                questions: [
                    { 
                        id: 'system-purpose', 
                        question: 'What is the primary purpose of this AI system?', 
                        type: 'text', 
                        required: true,
                        helpText: 'Describe the main function and intended use of the system'
                    },
                    { 
                        id: 'deployment-status', 
                        question: 'What is the current deployment status?', 
                        type: 'radio',
                        options: [
                            'Planning/Design phase',
                            'Development in progress',
                            'Testing/Validation',
                            'Deployed in production',
                            'Retired/Decommissioned'
                        ],
                        required: true 
                    },
                    {
                        id: 'user-base',
                        question: 'Who are the primary users or affected individuals?',
                        type: 'checkbox',
                        options: [
                            'Internal employees',
                            'External customers',
                            'General public',
                            'Vulnerable groups',
                            'Other stakeholders'
                        ],
                        required: true
                    }
                ]
            },
            {
                id: 'risk-assessment',
                title: 'Risk Assessment',
                description: 'Identify and evaluate potential risks',
                questions: [
                    { 
                        id: 'risk-documented', 
                        question: 'Have risks been formally documented?', 
                        type: 'yes-no', 
                        required: true,
                        helpText: 'Article 9 requires systematic risk identification and documentation'
                    },
                    {
                        id: 'risk-categories',
                        question: 'Which risk categories have been identified?',
                        type: 'checkbox',
                        options: [
                            'Safety risks',
                            'Privacy risks',
                            'Security risks',
                            'Fairness/Bias risks',
                            'Transparency risks',
                            'Environmental risks'
                        ],
                        required: true
                    },
                    { 
                        id: 'risk-severity', 
                        question: 'What is the overall risk severity level?', 
                        type: 'radio',
                        options: [
                            'Critical - Immediate action required',
                            'High - Significant risks identified',
                            'Medium - Moderate risks with mitigation',
                            'Low - Minimal risks',
                            'Not yet assessed'
                        ],
                        required: true 
                    }
                ]
            },
            {
                id: 'mitigation-measures',
                title: 'Mitigation Measures',
                description: 'Define risk mitigation and control measures',
                questions: [
                    { 
                        id: 'mitigation-plan', 
                        question: 'Is there a documented mitigation plan?', 
                        type: 'yes-no', 
                        required: true 
                    },
                    {
                        id: 'control-measures',
                        question: 'What control measures are implemented?',
                        type: 'checkbox',
                        options: [
                            'Technical safeguards',
                            'Procedural controls',
                            'Human oversight',
                            'Monitoring systems',
                            'Incident response procedures',
                            'Regular audits'
                        ],
                        required: true
                    },
                    {
                        id: 'mitigation-effectiveness',
                        question: 'Describe how mitigation effectiveness is measured',
                        type: 'text',
                        required: true
                    }
                ]
            },
            {
                id: 'compliance-requirements',
                title: 'Compliance Requirements',
                description: 'Verify compliance with applicable regulations',
                questions: [
                    {
                        id: 'applicable-regulations',
                        question: 'Which regulations apply to this system?',
                        type: 'checkbox',
                        options: [
                            'EU AI Act',
                            'GDPR',
                            'Industry-specific regulations',
                            'National laws',
                            'International standards',
                            'Not yet determined'
                        ],
                        required: true
                    },
                    {
                        id: 'compliance-status',
                        question: 'What is the current compliance status?',
                        type: 'radio',
                        options: [
                            'Fully compliant',
                            'Partially compliant - working towards full compliance',
                            'Non-compliant - remediation in progress',
                            'Not yet assessed'
                        ],
                        required: true
                    },
                    {
                        id: 'compliance-gaps',
                        question: 'Describe any identified compliance gaps',
                        type: 'text',
                        required: true
                    }
                ]
            },
            {
                id: 'monitoring-review',
                title: 'Monitoring and Review',
                description: 'Ongoing monitoring and periodic review processes',
                questions: [
                    {
                        id: 'monitoring-frequency',
                        question: 'How frequently is the system monitored?',
                        type: 'radio',
                        options: [
                            'Continuous real-time monitoring',
                            'Daily',
                            'Weekly',
                            'Monthly',
                            'Quarterly',
                            'No regular monitoring'
                        ],
                        required: true
                    },
                    {
                        id: 'review-process',
                        question: 'Is there a periodic review process?',
                        type: 'yes-no',
                        required: true,
                        helpText: 'Regular reviews ensure ongoing compliance and effectiveness'
                    },
                    {
                        id: 'improvement-actions',
                        question: 'What continuous improvement actions are planned?',
                        type: 'text',
                        required: true
                    }
                ]
            }
        ]
    }
};

// State
let riskState = {
    selectedToolId: null,
    projectId: (function() {
        const parts = window.location.pathname.split('/').filter(p => p);
        if (parts.length >= 2) {
            return parts[parts.length - 1];
        }
        return null;
    })(),
    mode: 'choice', // 'choice', 'ai-scan', 'questionnaire'
    currentSectionIndex: 0,
    answers: {},
    expandedQuestions: {},
    scanProgress: 0,
    scanComplete: false,
    scanInterval: null,
    scanReport: null,
    discoveredSkills: []
};

// Initialize Risk Evaluations Tab
function updateRiskEvaluations() {
    updateRiskStatusBlocks();
    renderRiskEvaluationsTools();
}

function updateRiskStatusBlocks() {
    // Logic to sync status blocks - SAME AS BEFORE
    const block1El = document.getElementById('risk-profile-block1');
    if (block1El) {
        let status = 'Not assessed';
        if (typeof block1State !== 'undefined' && block1State.status) status = block1State.status;
        
        if (status === 'Prohibited') {
            block1El.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#FFEBEE] text-[#C62828]";
        } else if (status === 'Not assessed') {
            block1El.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#F0F1F2] text-[#B5BCC4]";
        } else {
            block1El.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#E8F5E9] text-[#2E7D32]";
        }
        block1El.innerText = status;
    }
    
    // Block 2
    const block2El = document.getElementById('risk-profile-block2');
    if (block2El) {
        let status = typeof getHighRiskStatus === 'function' ? getHighRiskStatus() : 'Not assessed';
        if (status.includes('High-Risk') && !status.includes('Not')) {
             block2El.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#FFF3E0] text-[#E65100]";
        } else if (status === 'Not High-Risk' || status === 'Not Applicable') {
             block2El.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#E8F5E9] text-[#2E7D32]";
        } else {
             block2El.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#F0F1F2] text-[#B5BCC4]";
        }
        block2El.innerText = status;
    }

    // Block 4
    const block4El = document.getElementById('risk-profile-block4');
    const gpaiLevelEl = document.getElementById('risk-profile-gpai-level');
    if (block4El) {
        let status = typeof getGPAIStatus === 'function' ? getGPAIStatus() : 'Not assessed';
        if (status === 'Applies' || status === 'Triggered') {
             block4El.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#FFF3E0] text-[#E65100]";
             if(gpaiLevelEl) { gpaiLevelEl.innerText = 'Systemic Risk'; gpaiLevelEl.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#FFF3E0] text-[#E65100]"; }
        } else if (status === 'Not Applicable') {
             block4El.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#E8F5E9] text-[#2E7D32]";
             if(gpaiLevelEl) { gpaiLevelEl.innerText = 'N/A'; gpaiLevelEl.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#F0F1F2] text-[#B5BCC4]"; }
        } else {
             block4El.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#F0F1F2] text-[#B5BCC4]";
             if(gpaiLevelEl) { gpaiLevelEl.innerText = 'N/A'; gpaiLevelEl.className = "inline-flex px-3 py-1.5 rounded-full font-semibold text-sm bg-[#F0F1F2] text-[#B5BCC4]"; }
        }
        block4El.innerText = status;
    }
}

function renderRiskEvaluationsTools() {
    const container = document.getElementById('risk-eval-tools-list');
    if (!container) return;
    container.innerHTML = '';
    
    // Define the specific sections as per design requirements
    const sections = [
        {
            title: 'Cybersecurity',
            description: 'Standard cybersecurity best practices recommended to protect system integrity and user data.',
            color: '#F13D30', // Red
            tools: ['prompt-injection-detector', 'security-frameworks', 'grype-vulnerability', 'safety-pyup', 'snyk-io', 'oss-scorecard']
        },
        {
            title: 'Privacy',
            description: 'Standard privacy requirements. Ensure GDPR compliance and appropriate data protection measures.',
            color: '#7C3AED', // Purple
            tools: ['data-classification', 'gdpr-compliance', 'hipaa-compliance', 'pci-dss-compliance']
        },
        {
            title: 'Fundamental Rights Impact Assessment (FRIA)',
            description: 'FRIA recommended for systems with potential fundamental rights impact. Evaluate effects on privacy, equality, and human dignity to ensure compliance with EU Charter of Fundamental Rights.',
            color: '#2563EB', // Blue
            tools: ['fria-assessment', 'bias-assessment', 'ai-fairness-360', 'hitl-design']
        },
        {
            title: 'Societal',
            description: 'Assess potential societal impacts and ensure responsible deployment practices.',
            color: '#06B6D4', // Cyan/Teal
            tools: ['detoxify', 'hate-speech-detector', 'claimbuster-api', 'fact-checker', 'ai-content-detector', 'perspective-api-societal', 'textblob-sentiment', 'vader-sentiment']
        },
        {
            title: 'Fairness & Bias Detection',
            description: 'Monitor for potential bias. Implement measures to ensure fairness and non-discrimination.',
            color: '#DB2777', // Pink/Magenta
            tools: ['ai-fairness-360', 'fairlearn', 'aequitas', 'bias-assessment', 'disaggregated-evaluation', 'perspective-api', 'moderate-content-api']
        },
        {
            title: 'Trust & Explainability',
            description: 'Transparency obligations may apply. Consider implementing trust-building measures to enhance user confidence.',
            color: '#10B981', // Emerald Green
            tools: ['explainability-planning', 'shap-explainer', 'lime', 'captum', 'interpretml', 'what-if-tool', 'ai-transparency-labels', 'model-card-generation', 'hitl-design']
        },
        {
            title: 'Health and Safety',
            description: 'General health and safety considerations. Ensure system does not create unreasonable health risks. Implement appropriate safeguards to prevent harm.',
            color: '#DC2626', // Red
            tools: ['ai-safety', 'ai-safety-planning', 'red-team-testing', 'guardrails-implementation', 'risk-assessment', 'incident-responder']
        },
        {
            title: 'Performance Testing & Monitoring',
            description: 'Regular performance testing recommended. Monitor model accuracy, data quality, and system reliability.',
            color: '#8B5CF6', // Violet
            tools: ['evidently-ai', 'alibi-detect', 'ragas', 'deepeval', 'huggingface-evaluate', 'langsmith', 'weights-and-biases', 'promptfoo']
        },
        {
            title: 'Governance & Documentation',
            description: 'Registration requirements may apply. Verify obligations under Article 71 for transparency requirements.',
            color: '#F59E0B', // Amber/Orange
            tools: ['ai-ethics', 'ai-ethics-advisor', 'ai-governance', 'ethics-review', 'validating-ai-ethics-and-fairness', 'ai-logging-system', 'ai-system-registry', 'qms-tracker', 'ce-marking-generator']
        },
        {
            title: 'Environmental',
            description: 'Consider environmental sustainability. Optimize resource usage and energy efficiency where possible.',
            color: '#10B981', // Green
            tools: ['codecarbon', 'cloud-carbon-footprint', 'ml-co2-impact', 'watttime-carbon']
        }
    ];

    sections.forEach(section => {
        const sectionWrapper = document.createElement('div');
        sectionWrapper.className = "flex gap-4 mb-8"; // Main container for the section
        
        // Colored side bar
        const accentBar = document.createElement('div');
        accentBar.className = "w-1 shrink-0 rounded-full";
        accentBar.style.backgroundColor = section.color;
        
        // Content area
        const contentArea = document.createElement('div');
        contentArea.className = "flex-1 space-y-2";
        
        // Title
        const title = document.createElement('h3');
        title.style.margin = '0';
        title.className = "font-bold text-base text-[#22262A]";
        title.innerText = section.title;
        
        // Description
        const desc = document.createElement('p');
        desc.style.margin = '0';
        desc.className = "text-sm text-[#464E58]";
        desc.innerText = section.description;
        
        // Tools Container
        const toolsContainer = document.createElement('div');
        toolsContainer.className = "pt-2";
        
        const recommendedLabel = document.createElement('p');
        recommendedLabel.style.marginBottom = '8px';
        recommendedLabel.className = "text-xs font-semibold text-[#6B7280] uppercase";
        recommendedLabel.innerText = "Recommended Tools:";
        
        const toolsList = document.createElement('div');
        toolsList.className = "flex flex-wrap gap-2";
        
        section.tools.forEach(toolKey => {
            const tool = toolDescriptionsMap[toolKey];
            if (!tool) return; // Skip if tool not found in map
            
            const toolBtn = document.createElement('button');
            toolBtn.className = "px-3 py-1.5 bg-[#F9FAFB] border border-[#E5E7EB] rounded-md text-xs font-medium text-[#464E58] hover:border-[#B5BCC4] hover:bg-[#F3F4F6] transition-colors";
            toolBtn.innerText = tool.name;
            toolBtn.onclick = () => selectRiskTool(toolKey);
            
            toolsList.appendChild(toolBtn);
        });
        
        toolsContainer.appendChild(recommendedLabel);
        toolsContainer.appendChild(toolsList);
        
        // Assemble content area
        contentArea.appendChild(title);
        contentArea.appendChild(desc);
        contentArea.appendChild(toolsContainer);
        
        // Assemble section wrapper
        sectionWrapper.appendChild(accentBar);
        sectionWrapper.appendChild(contentArea);
        
        container.appendChild(sectionWrapper);
    });
}

// ==========================================
// CORE REFRACTOR: Skill Assessment Logic
// ==========================================

async function selectRiskTool(toolKey) {
    riskState.selectedToolId = toolKey;
    riskState.projectId = window.location.pathname.split('/').filter(p => p).pop(); // Get project_id from URL
    riskState.mode = 'choice';
    riskState.currentSectionIndex = 0;
    riskState.answers = {};
    riskState.expandedQuestions = {};
    riskState.scanProgress = 0;
    riskState.scanComplete = false;
    riskState.scanReport = null;
    if (riskState.scanInterval) clearInterval(riskState.scanInterval);

    // Switch views first
    document.getElementById('risk-eval-main-view').classList.add('hidden');
    document.getElementById('risk-eval-tool-view').classList.remove('hidden');
    
    // Show loading state
    const container = document.getElementById('risk-eval-tool-view-content');
    if (container) {
        container.innerHTML = `
            <div class="bg-white rounded-lg border border-[#F0F1F2] shadow-sm h-full flex flex-col items-center justify-center p-12">
                <div class="w-16 h-16 rounded-full bg-[#F13D30] bg-opacity-10 flex items-center justify-center mb-4 animate-pulse">
                    <svg class="w-8 h-8 text-[#F13D30] animate-spin" viewBox="0 0 24 24" fill="none">
                        <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                        <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                </div>
                <h3 class="font-bold text-lg text-[#22262A] mb-2">Discovering Available Skills...</h3>
                <p class="text-sm text-[#464E58]">Scanning AI Act skills packages</p>
            </div>
        `;
    }

    // Fetch available skills from BE to ensure connection
    try {
        const response = await fetch('/api/compliance/skills/');
        const data = await response.json();
        if (data.success) {
            riskState.discoveredSkills = data.skills;
        }
    } catch (e) {
        console.error("Failed to fetch skills:", e);
        // Show error state
        if (container) {
            container.innerHTML = `
                <div class="bg-white rounded-lg border border-[#F0F1F2] shadow-sm h-full flex flex-col items-center justify-center p-12">
                    <div class="w-16 h-16 rounded-full bg-red-100 flex items-center justify-center mb-4">
                        <svg class="w-8 h-8 text-red-600" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <circle cx="12" cy="12" r="10"></circle>
                            <line x1="15" y1="9" x2="9" y2="15"></line>
                            <line x1="9" y1="9" x2="15" y2="15"></line>
                        </svg>
                    </div>
                    <h3 class="font-bold text-lg text-[#22262A] mb-2">Failed to Load Skills</h3>
                    <p class="text-sm text-[#464E58] mb-4">Could not connect to skills package</p>
                    <button onclick="selectRiskTool('${toolKey}')" class="px-4 py-2 bg-[#F13D30] text-white rounded-lg font-medium hover:bg-[#D92D20] transition-colors">
                        Retry
                    </button>
                </div>
            `;
        }
        return;
    }

    renderRiskToolView();
}

function closeRiskTool() {
    riskState.selectedToolId = null;
    document.getElementById('risk-eval-main-view').classList.remove('hidden');
    document.getElementById('risk-eval-tool-view').classList.add('hidden');
}

function getAssessmentData() {
    const toolId = riskState.selectedToolId;
    const tool = toolDescriptionsMap[toolId];
    const defaultData = skillAssessments['default'];
    const specificData = skillAssessments[toolId] || defaultData;
    
    // Determine Article based on category if not explicitly defined in the assessment data
    let article = specificData.article;
    if (!article && tool) {
        const categoryArticles = {
            'Cybersecurity': 'Article 15',
            'Privacy': 'Article 10',
            'Fundamental Rights': 'Article 27',
            'Fairness': 'Article 10',
            'Trust': 'Article 13',
            'Governance': 'Article 17',
            'Performance': 'Article 15'
        };
        article = categoryArticles[tool.category];
    }
    
    return { ...specificData, article };
}

function getToolInfo() {
    return toolDescriptionsMap[riskState.selectedToolId] || { name: 'Unknown Tool', category: 'General', description: '' };
}

function renderRiskToolView() {
    const container = document.getElementById('risk-eval-tool-view-content');
    if (!container) return;
    
    if (riskState.mode === 'choice') {
        container.innerHTML = renderChoiceMode();
    } else if (riskState.mode === 'ai-scan-ready') {
        container.innerHTML = renderAIScanReadyMode();
    } else if (riskState.mode === 'ai-scan') {
        container.innerHTML = renderAIScanMode();
        // Trigger generic post-render logic if needed (e.g. for animations)
    } else if (riskState.mode === 'questionnaire') {
        container.innerHTML = renderQuestionnaireMode();
    }
}

// RENDER: Choice Mode
function renderChoiceMode() {
    const tool = getToolInfo();
    const assessment = getAssessmentData();
    
    return `
        <div class="bg-white rounded-lg border border-[#F0F1F2] shadow-sm">
            <div class="p-6 border-b border-[#F0F1F2]">
                <button onclick="closeRiskTool()" class="flex items-center gap-2 text-[#464E58] hover:text-[#22262A] mb-4 font-medium text-sm transition-colors">
                    <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>
                    Back to Risk Evaluations
                </button>
                <div class="inline-flex px-3 py-1 bg-[#F9FAFB] border border-[#E5E7EB] rounded-full text-xs font-medium text-[#464E58] mb-2">
                    ${tool.category} ${assessment.article ? ' • ' + assessment.article : ''}
                </div>
                <h1 class="font-bold text-2xl text-[#22262A] mb-2">${tool.name}</h1>
                <p class="text-sm text-[#464E58]">${tool.description}</p>
            </div>
            <div class="p-8">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-6 max-w-4xl mx-auto">
                    <!-- AI Scan Option -->
                    <button onclick="setRiskMode('ai-scan-ready')" class="group relative bg-[#FEFEFE] border border-[#E5E7EB] rounded-xl p-6 hover:border-[#F13D30] hover:shadow-md transition-all text-left h-full flex flex-col">
                         <div class="flex justify-between items-start mb-4 w-full">
                            <h3 class="font-bold text-xl text-[#22262A]">AI Agent Scan</h3>
                            <div class="w-10 h-10 rounded-full bg-[#F13D30] border border-[#E5E7EB] flex items-center justify-center shrink-0">
                                <img src="/static/governance/img/aiassistant.svg" alt="Sparkle" class="w-5 h-5 brightness-0 invert">
                            </div>
                         </div>
                         <p class="text-sm text-[#464E58] mb-6 leading-relaxed">Let our AI agents automatically scan and analyze your system to provide instant compliance insights.</p>
                         
                         <ul class="space-y-3 mb-6 flex-grow">
                            <li class="flex items-start gap-3 text-sm text-[#464E58]">
                                <svg class="w-5 h-5 text-[#F13D30] shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg>
                                <span>Automated analysis</span>
                            </li>
                            <li class="flex items-start gap-3 text-sm text-[#464E58]">
                                <svg class="w-5 h-5 text-[#F13D30] shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg>
                                <span>Instant results</span>
                            </li>
                            <li class="flex items-start gap-3 text-sm text-[#464E58]">
                                <svg class="w-5 h-5 text-[#F13D30] shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg>
                                <span>AI-powered recommendations</span>
                            </li>
                         </ul>

                         <div class="border-t border-[#E5E7EB] pt-4 flex items-center justify-between w-full mt-auto">
                            <span class="text-sm text-[#464E58] font-medium">Estimated time: ~2 minutes</span>
                            <span class="text-[10px] font-bold text-[#F13D30] bg-[#FEF2F2] px-2 py-1 rounded uppercase tracking-wide">RECOMMENDED</span>
                         </div>
                    </button>

                    <!-- Questionnaire Option -->
                    <button onclick="setRiskMode('questionnaire')" class="group relative bg-[#FEFEFE] border border-[#E5E7EB] rounded-xl p-6 hover:border-[#6B7280] hover:shadow-md transition-all text-left h-full flex flex-col">
                         <div class="flex justify-between items-start mb-4 w-full">
                            <h3 class="font-bold text-xl text-[#22262A]">Fill Questionnaire</h3>
                            <div class="w-10 h-10 rounded-full bg-white border border-[#E5E7EB] flex items-center justify-center shrink-0">
                                <svg class="w-5 h-5 text-[#464E58]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
                                    <polyline points="14 2 14 8 20 8"></polyline>
                                    <line x1="16" y1="13" x2="8" y2="13"></line>
                                    <line x1="16" y1="17" x2="8" y2="17"></line>
                                    <polyline points="10 9 9 9 8 9"></polyline>
                                </svg>
                            </div>
                         </div>
                         <p class="text-sm text-[#464E58] mb-6 leading-relaxed">Manually complete a comprehensive questionnaire for detailed assessment and full control.</p>
                         
                         <ul class="space-y-3 mb-6 flex-grow">
                            <li class="flex items-start gap-3 text-sm text-[#464E58]">
                                <svg class="w-5 h-5 text-[#6B7280] shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg>
                                <span>Detailed questions</span>
                            </li>
                            <li class="flex items-start gap-3 text-sm text-[#464E58]">
                                <svg class="w-5 h-5 text-[#6B7280] shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg>
                                <span>Complete control</span>
                            </li>
                            <li class="flex items-start gap-3 text-sm text-[#464E58]">
                                <svg class="w-5 h-5 text-[#6B7280] shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg>
                                <span>Section-by-section guidance</span>
                            </li>
                         </ul>

                         <div class="border-t border-[#E5E7EB] pt-4 flex items-center w-full mt-auto">
                            <span class="text-sm text-[#464E58] font-medium">Estimated time: ~15 minutes</span>
                         </div>
                    </button>
                </div>
            </div>
        </div>
    `;
}

function setRiskMode(mode) {
    riskState.mode = mode;
    renderRiskToolView();
    if (mode === 'ai-scan') {
        startAIScan();
    }
}

// Helper function to start the actual scan
function startActualAIScan() {
    setRiskMode('ai-scan');
}

// RENDER: AI Scan Ready Mode (Pre-scan)
function renderAIScanReadyMode() {
    const tool = getToolInfo();
    const assessment = getAssessmentData();
    
    return `
        <div class="bg-white rounded-lg border border-[#F0F1F2] shadow-sm h-full flex flex-col">
            <div class="p-6 border-b border-[#F0F1F2]">
                <button onclick="setRiskMode('choice')" class="flex items-center gap-2 text-[#464E58] hover:text-[#22262A] mb-4 font-medium text-sm transition-colors">
                    <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="15 18 9 12 15 6"></polyline></svg>
                    Back to Method Selection
                </button>
                <div class="inline-flex px-3 py-1 bg-[#F9FAFB] border border-[#E5E7EB] rounded-full text-xs font-medium text-[#464E58] mb-2">
                    ${tool.category} • AI Agent Scan
                </div>
                <h1 class="font-bold text-2xl text-[#22262A]">${tool.name}</h1>
            </div>
            <div class="flex-grow flex flex-col items-center justify-center p-12 text-center">
                 <div class="w-20 h-20 rounded-full bg-[#F13D30] flex items-center justify-center mb-6 shadow-md">
                    <img src="/static/governance/img/aiassistant.svg" alt="Start Scan" class="w-10 h-10 brightness-0 invert">
                </div>
                <h2 class="font-bold text-2xl text-[#22262A] mb-4">Ready to Scan</h2>
                <p class="text-[#464E58] max-w-lg mx-auto mb-6 leading-relaxed">
                    Our AI agents will analyze your system configuration, data flows, and compliance posture using the **${tool.name}** methodology.
                </p>
                
                ${riskState.discoveredSkills.some(s => s.id === riskState.selectedToolId || riskState.selectedToolId.includes(s.id)) ? `
                    <div class="mb-10 px-4 py-2 bg-[#F0FDF4] border border-[#DCFCE7] rounded-lg inline-flex items-center gap-2">
                        <svg class="w-4 h-4 text-[#16A34A]" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"></path><polyline points="22 4 12 14.01 9 11.01"></polyline></svg>
                        <span class="text-xs font-semibold text-[#166534]">Intelligence Source Connected: AI Act Skills Package</span>
                    </div>
                ` : ''}
                
                <div class="mb-10 w-full">
                    <button onclick="startActualAIScan()" class="bg-[#F13D30] hover:bg-[#D92D20] text-white px-8 py-3 rounded-lg font-bold shadow-lg shadow-red-200 transition-all flex items-center gap-3 mx-auto">
                        <img src="/static/governance/img/aiassistant.svg" alt="" class="w-5 h-5 brightness-0 invert">
                        Start AI Scan
                    </button>
                </div>
            </div>
        </div>
    `;
}

// RENDER: AI Scan Mode
async function startAIScan() {
    riskState.scanProgress = 0;
    riskState.scanComplete = false;
    riskState.scanReport = null;
    
    // Start visual progress simulation
    if (riskState.scanInterval) clearInterval(riskState.scanInterval);
    riskState.scanInterval = setInterval(() => {
        if (riskState.scanProgress < 90) {
            riskState.scanProgress += Math.floor(Math.random() * 5) + 1;
            renderRiskToolView();
        }
    }, 400);

    try {
        const response = await fetch('/api/compliance/ai-scan/', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': getCookie('csrftoken')
            },
            body: JSON.stringify({
                project_id: riskState.projectId,
                tool_id: riskState.selectedToolId
            })
        });

        const data = await response.json();
        
        if (data.success) {
            riskState.scanReport = data.report;
            riskState.scanProgress = 100;
            riskState.scanComplete = true;
        } else {
            showNotification('Scan failed: ' + data.error, 'error');
            setRiskMode('choice');
        }
    } catch (error) {
        console.error('Scan Error:', error);
        showNotification('An error occurred during scan', 'error');
        setRiskMode('choice');
    } finally {
        if (riskState.scanInterval) clearInterval(riskState.scanInterval);
        renderRiskToolView();
    }
}

// Helper to get CSRF token
function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

function renderAIScanMode() {
    const progress = riskState.scanProgress;
    const complete = riskState.scanComplete;
    const tool = getToolInfo();
    const report = riskState.scanReport;
    
    if (complete && report) {
        const scoreColor = report.score >= 80 ? '#10B981' : (report.score >= 50 ? '#F59E0B' : '#F13D30');
        const hasMarkdown = report.report_md && report.report_md.length > 0;
        const reportFile = report.report_file || '';
        const activeTab = riskState.reportTab || 'summary';

        // Convert markdown to simple HTML for rendering
        const mdHtml = hasMarkdown ? convertMarkdownToHtml(report.report_md) : '';

        return `
            <div class="bg-white rounded-lg border border-[#F0F1F2] shadow-sm">
                 <div class="p-6 border-b border-[#F0F1F2]">
                    <button onclick="setRiskMode('choice')" class="flex items-center gap-2 text-[#464E58] hover:text-[#22262A] mb-4 font-medium text-sm transition-colors">
                        <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>
                        Back
                    </button>
                    <div class="flex justify-between items-center">
                        <h1 class="font-bold text-2xl text-[#22262A]">${tool.name} • Report</h1>
                        <div class="flex items-center gap-2">
                            <span class="text-sm font-medium text-[#464E58]">Compliance Score:</span>
                            <div class="px-3 py-1 rounded-full font-bold text-white" style="background-color: ${scoreColor}">
                                ${report.score}%
                            </div>
                        </div>
                    </div>
                    <!-- Tab Switcher -->
                    <div class="flex gap-1 mt-4 bg-[#F3F4F6] rounded-lg p-1">
                        <button onclick="switchReportTab('summary')" class="flex-1 px-4 py-2 rounded-md text-sm font-medium transition-colors ${activeTab === 'summary' ? 'bg-white text-[#22262A] shadow-sm' : 'text-[#6B7280] hover:text-[#22262A]'}">
                            Summary View
                        </button>
                        <button onclick="switchReportTab('markdown')" class="flex-1 px-4 py-2 rounded-md text-sm font-medium transition-colors ${activeTab === 'markdown' ? 'bg-white text-[#22262A] shadow-sm' : 'text-[#6B7280] hover:text-[#22262A]'}" ${!hasMarkdown ? 'disabled' : ''}>
                            Full Report (MD)
                        </button>
                    </div>
                </div>

                ${activeTab === 'summary' ? `
                <div class="p-8 max-w-4xl mx-auto">
                    <div class="text-center mb-10">
                        <div class="w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-4" style="background-color: ${scoreColor}">
                            <svg class="w-8 h-8 text-white" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="20 6 9 17 4 12"></polyline></svg>
                        </div>
                        <h2 class="font-bold text-2xl text-[#22262A] mb-2">Scan Complete</h2>
                        <p class="text-sm text-[#464E58]">Status: <span class="font-bold">${report.compliance_status}</span></p>
                        ${report.risk_classification ? `<p class="text-xs text-[#9CA3AF] mt-1">Risk: <span class="font-bold">${typeof report.risk_classification === 'object' ? (report.risk_classification.category || JSON.stringify(report.risk_classification)) : report.risk_classification}</span></p>` : ''}
                    </div>

                    <!-- AI Analysis Summary -->
                    <div class="mb-10">
                        <h3 class="font-bold text-lg text-[#22262A] mb-4">AI Analysis Summary</h3>
                        <div class="bg-[#F9FAFB] rounded-2xl border border-[#F0F1F2] p-6">
                            <p class="text-[#464E58] leading-relaxed">${report.summary}</p>
                        </div>
                    </div>

                    <!-- Detailed Findings -->
                    <div class="mb-10">
                        <h3 class="font-bold text-lg text-[#22262A] mb-4">Detailed Findings</h3>
                        <div class="space-y-4">
                            ${(report.detailed_output || []).map(item => `
                                <div class="bg-white p-5 rounded-xl border border-[#F0F1F2] shadow-sm">
                                    <div class="flex justify-between items-start mb-2">
                                        <span class="px-2 py-0.5 bg-[#F3F4F6] text-[#4B5563] text-xs font-bold rounded uppercase">${item.category}</span>
                                        <span class="text-xs text-[#9CA3AF] font-medium">${item.id}</span>
                                    </div>
                                    <h4 class="font-bold text-[#22262A] mb-2">${item.finding}</h4>
                                    <div class="flex gap-3 items-start mt-3 pt-3 border-t border-[#F9FAFB]">
                                        <svg class="w-4 h-4 text-[#10B981] mt-0.5 shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="20 6 9 17 4 12"></polyline></svg>
                                        <p class="text-sm text-[#464E58]"><span class="font-bold text-[#10B981]">Recommendation:</span> ${item.recommendation}</p>
                                    </div>
                                </div>
                            `).join('')}
                        </div>
                    </div>

                    <!-- Recommended Skills -->
                    ${(report.recommended_skills && report.recommended_skills.length > 0) ? `
                    <div class="mb-10">
                        <h3 class="font-bold text-lg text-[#22262A] mb-4">Recommended Skills</h3>
                        <div class="flex flex-wrap gap-2">
                            ${report.recommended_skills.map(skill => `
                                <span class="px-3 py-1.5 bg-[#FEF2F2] text-[#991B1B] text-sm font-medium rounded-full border border-[#FECACA]">${typeof skill === 'string' ? skill : skill.skill || skill}</span>
                            `).join('')}
                        </div>
                    </div>
                    ` : ''}

                    <!-- Next Steps -->
                    <div class="mb-10">
                        <h3 class="font-bold text-lg text-[#22262A] mb-4">Recommended Next Steps</h3>
                        <div class="bg-[#EFF6FF] rounded-2xl border border-[#DBEAFE] p-6">
                            <ul class="space-y-3">
                                ${(report.next_steps || []).map(step => `
                                    <li class="flex items-center gap-3">
                                        <div class="w-1.5 h-1.5 rounded-full bg-[#3B82F6]"></div>
                                        <span class="text-sm text-[#1E40AF] font-medium">${step}</span>
                                    </li>
                                `).join('')}
                            </ul>
                        </div>
                    </div>

                    <div class="flex gap-4">
                         <button onclick="setRiskMode('ai-scan')" class="flex-1 px-6 py-3.5 bg-white border border-[#B5BCC4] text-[#464E58] rounded-xl font-bold text-base hover:bg-[#F9FAFB] transition-colors">Rescan</button>
                         <button onclick="downloadScanReport()" class="flex-1 px-6 py-3.5 bg-[#F13D30] text-white rounded-xl font-bold text-base hover:bg-[#DC180A] transition-colors flex items-center justify-center gap-2 shadow-lg shadow-red-100">
                             <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M4 16v1a2 2 0 002 2h12a2 2 0 002-2v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path>
                             </svg>
                             Export Report (.md)
                         </button>
                    </div>
                </div>
                ` : `
                <!-- Full Markdown Report Tab -->
                <div class="p-8 max-w-4xl mx-auto">
                    <div class="prose prose-sm max-w-none scan-report-md" style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;">
                        ${mdHtml}
                    </div>
                    <div class="flex gap-4 mt-8 pt-6 border-t border-[#F0F1F2]">
                         <button onclick="setRiskMode('ai-scan')" class="flex-1 px-6 py-3.5 bg-white border border-[#B5BCC4] text-[#464E58] rounded-xl font-bold text-base hover:bg-[#F9FAFB] transition-colors">Rescan</button>
                         <button onclick="downloadScanReport()" class="flex-1 px-6 py-3.5 bg-[#F13D30] text-white rounded-xl font-bold text-base hover:bg-[#DC180A] transition-colors flex items-center justify-center gap-2 shadow-lg shadow-red-100">
                             <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" stroke-width="2">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M4 16v1a2 2 0 002 2h12a2 2 0 002-2v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path>
                             </svg>
                             Export Report (.md)
                         </button>
                    </div>
                </div>
                `}
            </div>
        `;
    }
    
    // Determine which tasks are complete based on progress
    const tasks = [
        { label: 'Analyzing system configuration', threshold: 25 },
        { label: 'Reviewing data flows', threshold: 50 },
        { label: 'Checking compliance requirements', threshold: 75 },
        { label: 'Generating recommendations', threshold: 100 }
    ];
    
    return `
        <div class="bg-white rounded-lg border border-[#F0F1F2] shadow-sm h-full flex flex-col">
            <div class="flex-grow flex flex-col items-center justify-center p-12 text-center">
                 <div class="w-20 h-20 rounded-full bg-[#FCA5A5] flex items-center justify-center mb-6 shadow-md animate-pulse">
                    <img src="/static/governance/img/aiassistant.svg" alt="Scanning" class="w-10 h-10 text-white">
                </div>
                <h2 class="font-bold text-2xl text-[#22262A] mb-4">Scanning in Progress...</h2>
                <p class="text-[#464E58] mb-10">AI agents are analyzing your system</p>
                
                <div class="w-full max-w-2xl mb-8">
                    <div class="flex justify-between text-sm font-medium text-[#22262A] mb-2">
                        <span>Progress</span>
                        <span>${progress}%</span>
                    </div>
                    <div class="w-full h-2 bg-[#E5E7EB] rounded-full overflow-hidden">
                        <div class="h-full bg-[#F13D30] transition-all duration-300" style="width: ${progress}%"></div>
                    </div>
                </div>
                
                <div class="w-full max-w-2xl space-y-4">
                    ${tasks.map(task => `
                        <div class="flex items-center gap-3 text-left ${progress >= task.threshold ? '' : 'opacity-50'}">
                            <svg class="w-5 h-5 ${progress >= task.threshold ? 'text-[#F13D30]' : 'text-[#9CA3AF]'} shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <polyline points="20 6 9 17 4 12"></polyline>
                            </svg>
                            <span class="text-[#22262A]">${task.label}</span>
                        </div>
                    `).join('')}
                </div>
            </div>
        </div>
    `;
}

// RENDER: Questionnaire Mode
function renderQuestionnaireMode() {
    const assessment = getAssessmentData();
    const sectionIndex = riskState.currentSectionIndex;
    const section = assessment.sections[sectionIndex];
    if (!section) return '<div class="p-4">Error: Section not found</div>';
    
    // Check if section is complete to enable next button
    const isSectionComplete = section.questions.filter(q => q.required).every(q => {
        const val = riskState.answers[q.id];
        return val && (Array.isArray(val) ? val.length > 0 : val.toString().trim() !== '');
    });

    let html = `
        <div class="bg-white rounded-lg border border-[#F0F1F2] shadow-sm">
             <div class="p-6 border-b border-[#F0F1F2]">
                <button onclick="setRiskMode('choice')" class="flex items-center gap-2 text-[#464E58] hover:text-[#22262A] mb-4 font-medium text-sm transition-colors">
                    <svg class="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>
                    Back
                </button>
                <div class="flex justify-between items-start">
                    <div>
                        <div class="inline-flex px-3 py-1 bg-[#F9FAFB] border border-[#E5E7EB] rounded-full text-xs font-medium text-[#464E58] mb-2">
                             ${assessment.category}
                        </div>
                        <h1 class="font-bold text-2xl text-[#22262A] mb-2">${assessment.name}</h1>
                        <p class="text-sm text-[#464E58]">${assessment.description}</p>
                    </div>
                </div>
                
                <div class="mt-6">
                    <div class="flex justify-between text-xs font-medium text-[#464E58] mb-2">
                        <span>Section ${sectionIndex + 1} of ${assessment.sections.length}</span>
                        <span>${Math.round(((sectionIndex + 1) / assessment.sections.length) * 100)}% Complete</span>
                    </div>
                    <div class="w-full h-2 bg-[#F0F1F2] rounded-full overflow-hidden">
                        <div class="h-full bg-[#F13D30] transition-all duration-300" style="width: ${((sectionIndex + 1) / assessment.sections.length) * 100}%"></div>
                    </div>
                </div>
             </div>
             
             <div class="p-6">
                <div class="mb-6">
                    <h2 class="font-bold text-xl text-[#22262A] mb-2">${section.title}</h2>
                    <p class="text-sm text-[#464E58]">${section.description}</p>
                </div>
                
                <div class="space-y-6">
                    ${section.questions.map(q => renderQuestion(q)).join('')}
                </div>
             </div>
             
             <div class="p-6 border-t border-[#F0F1F2] flex justify-between">
                <button onclick="changeSection(-1)" ${sectionIndex === 0 ? 'disabled' : ''} class="px-6 py-2.5 bg-white border border-[#B5BCC4] text-[#464E58] rounded-lg font-semibold text-sm hover:bg-[#F0F1F2] disabled:opacity-50">Previous</button>
                
                ${sectionIndex < assessment.sections.length - 1 
                  ? `<button onclick="changeSection(1)" ${!isSectionComplete ? 'disabled' : ''} class="px-6 py-2.5 bg-[#F13D30] text-white rounded-lg font-semibold text-sm hover:bg-[#DC180A] disabled:opacity-50 disabled:cursor-not-allowed">Next Section</button>`
                  : `<button onclick="finishQuestionnaire()" ${!isSectionComplete ? 'disabled' : ''} class="px-6 py-2.5 bg-[#F13D30] text-white rounded-lg font-semibold text-sm hover:bg-[#DC180A] disabled:opacity-50">Complete Assessment</button>`
                }
             </div>
        </div>
    `;
    return html;
}

function renderQuestion(q) {
    const val = riskState.answers[q.id];
    
    let inputHtml = '';
    if (q.type === 'yes-no') {
        const isYes = val === 'yes';
        const isNo = val === 'no';
        inputHtml = `
            <div class="flex gap-4">
                <button onclick="handleQuestionAnswer('${q.id}', 'yes')" class="flex-1 px-4 py-2 rounded-lg border font-medium text-sm transition-colors ${isYes ? 'bg-[#F13D30] border-[#F13D30] text-white' : 'bg-white border-[#E5E7EB] text-[#464E58] hover:border-[#F13D30]'}">Yes</button>
                <button onclick="handleQuestionAnswer('${q.id}', 'no')" class="flex-1 px-4 py-2 rounded-lg border font-medium text-sm transition-colors ${isNo ? 'bg-[#F13D30] border-[#F13D30] text-white' : 'bg-white border-[#E5E7EB] text-[#464E58] hover:border-[#F13D30]'}">No</button>
            </div>
        `;
    } else if (q.type === 'text') {
        inputHtml = `<textarea onchange="handleQuestionAnswer('${q.id}', this.value)" class="w-full h-24 px-4 py-3 border border-[#E5E7EB] rounded-lg text-sm focus:ring-2 focus:ring-[#F13D30] outline-none resize-none" placeholder="Enter your response...">${val || ''}</textarea>`;
    } else if (q.type === 'radio' && q.options) {
        inputHtml = `<div class="space-y-2">
            ${q.options.map(opt => `
                <label class="flex items-center gap-3 p-3 border border-[#E5E7EB] rounded-lg hover:bg-[#F9FAFB] cursor-pointer">
                    <input type="radio" name="${q.id}" ${val === opt ? 'checked' : ''} onchange="handleQuestionAnswer('${q.id}', '${opt}')" class="text-[#F13D30] focus:ring-[#F13D30]">
                    <span class="text-sm text-[#22262A]">${opt}</span>
                </label>
            `).join('')}
        </div>`;
    } else if (q.type === 'checkbox' && q.options) {
        const currVal = Array.isArray(val) ? val : [];
        inputHtml = `<div class="space-y-2">
            ${q.options.map(opt => {
                const checked = currVal.includes(opt);
                return `
                <label class="flex items-center gap-3 p-3 border border-[#E5E7EB] rounded-lg hover:bg-[#F9FAFB] cursor-pointer">
                    <input type="checkbox" ${checked ? 'checked' : ''} onchange="handleCheckboxAnswer('${q.id}', '${opt}', this.checked)" class="text-[#F13D30] focus:ring-[#F13D30] rounded">
                    <span class="text-sm text-[#22262A]">${opt}</span>
                </label>
                `;
            }).join('')}
        </div>`;
    }

    return `
        <div class="space-y-3">
            <div class="flex items-start gap-2">
                <label class="font-semibold text-sm text-[#22262A]">${q.question} ${q.required ? '<span class="text-[#F13D30]">*</span>' : ''}</label>
            </div>
            ${q.helpText ? `<p class="text-xs text-[#6B7280] italic">${q.helpText}</p>` : ''}
            ${inputHtml}
        </div>
    `;
}

function handleQuestionAnswer(qId, val) {
    riskState.answers[qId] = val;
    renderRiskToolView(); // Re-render to update UI state (buttons, next capability)
}

function handleCheckboxAnswer(qId, option, checked) {
    let current = riskState.answers[qId] || [];
    if (!Array.isArray(current)) current = [];
    
    if (checked) {
        if (!current.includes(option)) current.push(option);
    } else {
        current = current.filter(o => o !== option);
    }
    
    riskState.answers[qId] = current;
    renderRiskToolView();
}

function changeSection(delta) {
    riskState.currentSectionIndex += delta;
    renderRiskToolView();
}

function finishQuestionnaire() {
    showNotification('Assessment Questionnaire Completed!', 'success');
    closeRiskTool();
}

function saveRiskToolOutput() {
    downloadScanReport();
}

// Switch between Summary and Markdown report tabs
function switchReportTab(tab) {
    riskState.reportTab = tab;
    renderRiskToolView();
}

// Download scan report as .md file
function downloadScanReport() {
    const report = riskState.scanReport;
    if (!report) {
        showNotification('No report available to download', 'error');
        return;
    }

    // If server saved a file, download from server URL
    if (report.report_file) {
        const link = document.createElement('a');
        link.href = report.report_file + '?download=true';
        link.download = report.report_file.split('/').pop();
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        showNotification('Report downloaded successfully!', 'success');
        return;
    }

    // Fallback: generate MD from report_md content or build from JSON
    const mdContent = report.report_md || buildMarkdownFromReport(report);
    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `scan_report_${riskState.selectedToolId || 'unknown'}_${new Date().toISOString().slice(0,10)}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    showNotification('Report downloaded successfully!', 'success');
}

// Build markdown from JSON report (fallback if report_md not available)
function buildMarkdownFromReport(report) {
    let md = `# AI Act Compliance Scan Report\n\n`;
    md += `**Score:** ${report.score || 0}/100\n`;
    md += `**Status:** ${report.compliance_status || 'Unknown'}\n`;
    if (report.risk_classification) md += `**Risk:** ${report.risk_classification}\n`;
    md += `\n---\n\n## Summary\n\n${report.summary || 'No summary.'}\n`;
    md += `\n---\n\n## Detailed Findings\n\n`;
    if (report.detailed_output && report.detailed_output.length) {
        md += '| ID | Category | Finding | Recommendation |\n';
        md += '|----|----------|---------|----------------|\n';
        report.detailed_output.forEach(item => {
            md += `| ${item.id} | ${item.category} | ${item.finding} | ${item.recommendation} |\n`;
        });
    }
    md += `\n---\n\n## Next Steps\n\n`;
    if (report.next_steps) {
        report.next_steps.forEach((step, i) => { md += `${i+1}. ${step}\n`; });
    }
    return md;
}

// Convert Markdown to HTML for inline rendering (lightweight, no external lib)
function convertMarkdownToHtml(md) {
    if (!md) return '';
    let html = md;

    // Escape HTML entities first
    html = html.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

    // Headers
    html = html.replace(/^### (.+)$/gm, '<h3 class="text-lg font-bold text-[#22262A] mt-6 mb-3">$1</h3>');
    html = html.replace(/^## (.+)$/gm, '<h2 class="text-xl font-bold text-[#22262A] mt-8 mb-4 pb-2 border-b border-[#F0F1F2]">$1</h2>');
    html = html.replace(/^# (.+)$/gm, '<h1 class="text-2xl font-bold text-[#22262A] mb-6">$1</h1>');

    // Bold and italic
    html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
    html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');

    // Horizontal rules
    html = html.replace(/^---$/gm, '<hr class="my-6 border-[#F0F1F2]">');

    // Tables - handle more robustly
    html = html.replace(/^\|(.+)\|$/gm, function(match) {
        const cells = match.split('|').filter((c, i, a) => i > 0 && i < a.length - 1);
        if (cells.every(c => /^[\s\-:]+$/.test(c))) {
            return '<!--table-separator-->';
        }
        const row = cells.map(c => `<td class="px-4 py-3 border border-[#E5E7EB] text-sm align-top leading-relaxed">${c.trim()}</td>`).join('');
        return `<tr>${row}</tr>`;
    });

    // Wrap table rows
    html = html.replace(/((<tr>.*<\/tr>\n?)+)/g, function(match) {
        const cleaned = match.replace(/<!--table-separator-->\n?/g, '');
        if (!cleaned.trim()) return '';
        
        const rows = cleaned.trim().split('\n').filter(r => r.trim());
        if (rows.length > 0) {
            let tableHtml = '<div class="overflow-x-auto my-6 border border-[#E5E7EB] rounded-xl shadow-sm">';
            tableHtml += '<table class="w-full border-collapse text-sm table-auto">';
            
            // First row as header
            const headerRow = rows[0].replace(/<td class="[^"]*"/g, '<th class="px-4 py-3 bg-[#F9FAFB] border-b border-[#E5E7EB] font-bold text-[#22262A] text-left"')
                                      .replace(/<\/td>/g, '</th>');
            tableHtml += `<thead>${headerRow}</thead>`;
            tableHtml += `<tbody>${rows.slice(1).join('\n')}</tbody>`;
            tableHtml += '</table></div>';
            return tableHtml;
        }
        return match;
    });
    html = html.replace(/<!--table-separator-->\n?/g, '');

    // Ordered lists
    html = html.replace(/^(\d+)\. (.+)$/gm, '<li class="ml-6 mb-2 list-decimal text-sm text-[#464E58]">$2</li>');

    // Unordered lists
    html = html.replace(/^- (.+)$/gm, '<li class="ml-6 mb-2 list-disc text-sm text-[#464E58]">$1</li>');

    // Wrap consecutive <li> elements
    html = html.replace(/((<li[^>]*>.*<\/li>\n?)+)/g, '<ul class="mb-4 space-y-1">$1</ul>');

    // Blockquotes
    html = html.replace(/^&gt; (.+)$/gm, '<blockquote class="pl-4 border-l-4 border-[#F59E0B] bg-[#FFFBEB] p-4 rounded-r-lg my-6 text-sm text-[#92400E] italic shadow-sm">$1</blockquote>');

    // Paragraphs (lines that are not already wrapped)
    html = html.replace(/^(?!<(h[123]|ul|table|hr|block|div|li))(.+)$/gm, '<p class="text-sm text-[#464E58] leading-relaxed mb-4">$2</p>');

    // Clean empty paragraphs or nested tags
    html = html.replace(/<p[^>]*>\s*<\/p>/g, '');

    return html;
}

